<?php

namespace Magium\Magento;

use Magium\AbstractTestCase;
use Magium\InvalidConfigurationException;
use Magium\Magento\Themes\AbstractThemeConfiguration;
use Magium\Util\TestCase\RegistrationListener;

abstract class AbstractMagentoTestCase extends AbstractTestCase
{

    protected function setUp()
    {
        self::addBaseNamespace('Magium\Magento');
        RegistrationListener::addCallback(new Registration(), 100);
        parent::setUp();
    }

    /**
     * @param $method
     * @return \Magium\Magento\Actions\Checkout\PaymentMethods\PaymentMethodInterface
     */

    public function setPaymentMethod($method)
    {

        // If we are passed just the class name we will prepend it with Magium\Magento\Actions\Checkout\PaymentMethods
        if (strpos($method, '\\') === false) {
            $method = 'Magium\Magento\Actions\Checkout\PaymentMethods\\' . $method;
        }

        if (is_subclass_of($method, 'Magium\Magento\Actions\Checkout\PaymentMethods\PaymentMethodInterface')) {

            $this->setTypePreference('Magium\Magento\Actions\Checkout\PaymentMethods\PaymentMethodInterface', $method);
        } else {
            throw new InvalidConfigurationException('The payment method must implement Magium\Magento\Actions\Checkout\PaymentMethods\PaymentMethodInterface');
        }
    }

    /**
     * This is more of a helper for code completion
     *
     * @param null $theme
     * @return AbstractThemeConfiguration
     */

    public function getTheme($theme = null)
    {
        return parent::getTheme($theme); // TODO: Change the autogenerated stub
    }

    /**
     * @param $method
     * @return \Magium\Magento\Actions\Checkout\ShippingMethods\ShippingMethodInterface
     */

    public function setShippingMethod($method)
    {

        // If we are passed just the class name we will prepend it with Magium\Magento\Actions\Checkout\PaymentMethods
        if (strpos($method, '\\') === false) {
            $method = 'Magium\Magento\Actions\Checkout\ShippingMethods\\' . $method;
        }

        if (is_subclass_of($method, 'Magium\Magento\Actions\Checkout\ShippingMethods\ShippingMethodInterface')) {

            $this->setTypePreference('Magium\Magento\Actions\Checkout\PaymentMethods\ShippingMethodInterface', [$method]);
        } else {
            throw new InvalidConfigurationException('The payment method must implement Magium\Magento\Actions\Checkout\ShippingMethods\ShippingMethodInterface');
        }
    }

    public function switchThemeConfiguration($fullyQualifiedClassName)
    {
        $reflection = new \ReflectionClass($fullyQualifiedClassName);
        if ($reflection->isSubclassOf('Magium\Magento\Themes\NavigableThemeInterface')) {
            // Not entirely sure of hardcoding the various interface types.  May make this configurable
            parent::switchThemeConfiguration($fullyQualifiedClassName);
            $this->setTypePreference('Magium\Magento\Themes\AbstractThemeConfiguration',$fullyQualifiedClassName);
            $this->setTypePreference('Magium\Magento\Themes\NavigableThemeInterface',$fullyQualifiedClassName);
            $this->setTypePreference('Magium\Themes\BaseThemeInterface',$fullyQualifiedClassName);

            $this->setTypePreference('Magium\Magento\Themes\Customer\AbstractThemeConfiguration',$this->getTheme()->getCustomerThemeClass());
            $this->setTypePreference('Magium\Magento\Themes\OnePageCheckout\AbstractThemeConfiguration',$this->getTheme()->getCheckoutThemeClass());


        } else {
            throw new InvalidConfigurationException('The theme configuration extend Magium\Magento\Themes\NavigableThemeInterface');
        }

    }

}
