<?php

namespace Tests\Magium\Magento2\Customer;

use Magium\Magento\Themes\Magento2\ThemeConfiguration;

class ToCustomerLoginTest extends \Tests\Magium\Magento\Customer\ToCustomerLoginTest
{
    protected $pageHeader = 'Customer Login';

    protected function setUp()
    {
        parent::setUp();
        $this->switchThemeConfiguration(ThemeConfiguration::THEME);
    }

    public function testLoginCustomerFailsWhenRequireLoginIsSetAndAccountIsAlreadyLoggedIn()
    {
        parent::testLoginCustomerFailsWhenRequireLoginIsSetAndAccountIsAlreadyLoggedIn(); // TODO: Change the autogenerated stub
    }

    public function testLoginCustomerSucceedsWhenRequireLoginIsNotSetAndAccountIsAlreadyLoggedIn()
    {
        parent::testLoginCustomerSucceedsWhenRequireLoginIsNotSetAndAccountIsAlreadyLoggedIn(); // TODO: Change the autogenerated stub
    }
}